version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    links:
      - db:dbhost
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
  db:
    image: postgres:11.3
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
